from mdbx.mdbx import MDBXDBFlags

DB_CLAZZ_IDX = bytes(b'_clazz_idx')
DB_CLAZZ_IDX_FLAGS = MDBXDBFlags.MDBX_DB_DEFAULTS

DB_UNRESOLVED = bytes(b'_unresolved')
DB_UNRESOLVED_FLAGS = MDBXDBFlags.MDBX_INTEGERKEY | MDBXDBFlags.MDBX_DUPSORT

DB_ID_IDX = bytes(b'_id_idx')
DB_ID_IDX_FLAGS = MDBXDBFlags.MDBX_DB_DEFAULTS

DB_REFERENCE_OUTWARD = bytes(b'_reference_outward')
DB_REFERENCE_OUTWARD_FLAGS = MDBXDBFlags.MDBX_INTEGERKEY | MDBXDBFlags.MDBX_DUPSORT | MDBXDBFlags.MDBX_DUPFIXED | MDBXDBFlags.MDBX_INTEGERDUP

DB_REFERENCE_INWARD = bytes(b'_reference_inwards')
DB_REFERENCE_INWARD_FLAGS = MDBXDBFlags.MDBX_INTEGERKEY | MDBXDBFlags.MDBX_DUPSORT | MDBXDBFlags.MDBX_DUPFIXED | MDBXDBFlags.MDBX_INTEGERDUP

DB_EMBEDDED_ID_IDX = bytes(b'_embedded_id_idx')
DB_EMBEDDED_ID_IDX_FLAGS = MDBXDBFlags.MDBX_DB_DEFAULTS
